name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  verify-lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install & verify lock
        run: npm ci --dry-run
